# Generated by Django 4.0 on 2022-01-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=25)),
                ('watchlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist')),
            ],
        ),
    ]
