# Generated by Django 4.0 on 2022-01-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='watchlist_id',
            new_name='watchlist',
        ),
    ]
