# Generated by Django 4.0 on 2022-01-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
        ('stock', '0002_rename_watchlist_id_stock_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='watchlist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist'),
        ),
    ]
