# Generated by Django 4.0.1 on 2022-02-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchliststocks_watchlist_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistStocks',
        ),
    ]
