# Generated by Django 4.0.1 on 2022-01-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='owner',
        ),
    ]
